### PR TITLE
Php upload

### PR DESCRIPTION
**Pull request by dave-mills**
I've got this to the point where it's worth a review:

### Upload Process
- The uploader works fine for davis .txt files of any size;
- The import process is queued:
 - When the user clicks "Subir", the file is POSTED to the FileController::store() method.
 - A new File record is created
 - The PreProcessDavisHeaders() processor is run, which merges lines 1 and 2 into a single header row, ready for Laravel Excel Import. 
 - The processor also counts the number of records in the file, so we can add that to the File database entry. 
 - Then the import is queued and a 'MetDataImportStarted' event is triggered.
 - At the end of the import jobs, the MetDataImportComplete job is run, which calculates the number of new vs duplicate records and calls an event.

The front-end listens for these events and presents the appropriate notifications.

### Confirm / Cancel Processes
These have been tidied slightly.

### General Tidying
I have moved to using our default **laravel-file-utils** package to handle the storing of the data and observation files. This has allowed me to remove the `observations` table and model entirely, and now the observation_file is just stored on the files table (in the usual way i.e. as the path to the file).

I have also begun to remove some of the old bootstrap-vue components and replace them with regular <div> tags with bootstrap classes. 

## Tests vs Queues
Unfortunately, the tests prepared to confirm the Python scripts and these scripts have the same functionality won't work, as queued processes by can't be run during a test. To run a queue for real in a test, it must use the 'sync' driver, and many things work differently when synced - e.g. the Excel Import doesn't correctly queue the next chunks when running in sync. 

The alternative is to use mocking or faking ([Queue::fake()](https://laravel.com/docs/9.x/mocking#queue-fake)) and separate the testing of the job functionality and the fact that the job gets called during the post request. 

All this means that I don't know the best way to write these automated tests - we definitely cannot do a direct comparison because the tests will need to be different for the different upload processes. So for now, I think we can focus on tidying up this, adding the link to generate the summaries and improve the UX a bit. 

We can still use the test files in `tests/Files` as our test case files. 

## TODO
There are still many things to do here - particularly testing handling for error cases - e.g. where the uploaded file isn't in the correct format. 

 - [x] confirm that useful errors are presented if the file is not in the correct format;
 - [x] add "max temp" , "min temp" to the review section to highlight if the temperature range is sensible. (This has been on the list for ages)
 - [x] update stored procedures to generate summaries for just date-range + station of new data
 - [x] link 'confirm' function to summary generation
 - [x] create server events to show completion of summary generation on front-end. 
 - [x] complete revisions of UI to tidy front-end
 - [x] add handling for chinas stations (deliberately put last as UMSA are focused on the davis data)

### CODE REVIEW

**Comment by dan-tang-ssd** [comment]
I am going to upload one sample met data file for all stations as a sample check.

For station 1 file, I found something maybe incorrect during data upload...
[01.txt](https://github.com/stats4sd/red-de-redes/files/9056006/01.txt)

There are 1384 lines in this file:
 - line 1 and line 2: column headers
 - line 3 to line 1383: data records (1383 - 3 + 1 = 1381 records)
 - line 4: blank line

In file upload process, it shows there are 1382 records. (It should be 1381 I think...)
I guess it is the total number of lines after merging 2 lines of headers into 1 line
image

Total number of records remains 1382 records, until data file upload process is finished.
Both number of records and total number of records changed to 1381.
image

In database files table, the value of columns new_records_count, duplicate_record_count, total_records_count seem incorrect
I uploaded the same file twice with same values in these columns, I guess the data moving from met_data_preview to met_data is WIP so these data values will be properly set soon.
image

**Comment by dan-tang-ssd** [comment]
For station 3 (chinas), I tried to upload a .txt file and a .csv file (copy from station 14).
[03.txt](https://github.com/stats4sd/red-de-redes/files/9056167/03.txt)
[03_fake.csv](https://github.com/stats4sd/red-de-redes/files/9056174/03_fake.csv)

Clicked "Submit" button, with no response...
There are files records created only.

Not sure whether chinas met data file will be handled in a later stage.

image

image

**Comment by dan-tang-ssd** [comment]
For station 9 met data file:
[09.txt](https://github.com/stats4sd/red-de-redes/files/9056300/09.txt)

This is the first data file that shows first 10 records preview after data upload.

When all records are existing records, can we disable the GREEN "Confirm" button?
Because error occured when the "Confirm" button is clicked...

image

image

**Comment by dan-tang-ssd** [comment]
For station 11 met data file:
[11.txt](https://github.com/stats4sd/red-de-redes/files/9056339/11.txt)

1. At the end of upload process, number of records shows 5980 while there are only 5979 records in file...
2. First 10 records preview not showed after data upload... is the preview triggered by an event? When I manually click to view preview panel, preview data is here

image

image

image

**Comment by dan-tang-ssd** [comment]
All testing met data files can be found in below .zip file
[data_upload_testing_files.zip](https://github.com/stats4sd/red-de-redes/files/9056455/data_upload_testing_files.zip)

**Comment by dave-mills** [comment]
The Laravel Excel import validation was a bit tricky to impliment with the queuing:

- The only way to get the exact validation errors thrown from the `DavisFileImport` class was to include `SkipsOnFailure`, which keeps running the entire import and then lets you handle the errors at the end. 
  - This is not great when the issue is a missing or incorrect column header, (e.g., the "Date" column is mislabeled), as then there will be *n* identical validation errors. This makes it harder to present the errors. It's also a waste of time for larger files, as the system would take time processing the entire file just to give you an error that could have been known at the start. 
- The alternative option was to not use `SkipsOnFailure`, which doesn't complete the import after an error, but I was unable to retrieve the actual validation errors so the user would only see a generic error.

#### The solution - a 2nd importer, which *only* looks for column header errors

- I updated the `PreProcessDavisHeaders` class to generate a 2nd file, containing just the column headers and a single record. 
- Before the main import is queued, this extra file is processed by a new `DavisFileHeaderValidation` Import class. This class does no actual importing, but it has the validation rules enabled. Because it is run in sync and not on the queue, the exception is thrown immediately and the POST request fails with a 422 ( validation error). The front-end then handles this failure by presenting the validation errors to the user. 

I think this works quite well, as we check the file has the correct column headers *before* starting the actual import process. 

**Note** - for now, the only validation rules are that `date` and `time` are required columns. The other variables can be null in the database, so I don't think we need to check for them explicitly at this time.

**Comment by dave-mills** [comment]
I think, if this looks good, we can merge this into staging to test there this afternoon. 

Then before tomorrow, I'll ask Ciara to check the various messages and translate into Spanish, so we can publish it to live ready for tomorrow's meeting. I'll hold back on refactoring the UploaderWeatherData.vue file to tidy up some of the code and front-end formatting for now!

**Comment by dan-tang-ssd** [comment]
Found 16 new met data files that UMSA uploaded to live env in Apr and May 2022:
Normaly they have filesize 1.6 MB - 2 MB.

They can be found in remote server directory:
/home/forge/weatherstations.stats4sd.org/public/storage/rawfiles/backup_20220624

For convenience, please find these files for testing here:
[newfiles.zip](https://github.com/stats4sd/red-de-redes/files/9064854/newfiles.zip)

image

**Comment by dave-mills** [comment]
I think I've resolved that issue, where *every* file was returning a validation error - see my latest commit. 

@dan-tang-ssd - I'll test this with a set of those newer upload files and then we can deploy it first thing tomorrow?

**Comment by dave-mills** [comment]
Oh, yes - thanks! Pushed :)

**Comment by dan-tang-ssd** [comment]
Performed testing for station 1.
Some records are already existed, click the "I confirm" checkbox, click "Confirm" button.
Then error occured for duplicated record...

image

image

**Comment by dan-tang-ssd** [comment]
Performed testing for station 1, with met data file containing incorrect column header by changing "Date" to "Dte".
[01_incorrect_column_header.txt](https://github.com/stats4sd/red-de-redes/files/9069871/01_incorrect_column_header.txt)

Generic error message and specific error message showed before processing file in queue.

image

image

**Comment by dan-tang-ssd** [comment]
Performed testing for station 1, with met data file containing incorrect column header by changing "Time" to "Tme".

[01_incorrect_column_header_time.txt](https://github.com/stats4sd/red-de-redes/files/9069931/01_incorrect_column_header_time.txt)

Generic error message and specific error message showed before processing file in queue.

image

image

**Comment by dan-tang-ssd** [comment]
[PASSED]

Performed testing for station 1, with met data file containing incorrect column headers by changing "Date" to "Dte" and "Time" to "Tme".

[01_incorrect_column_header_date_and_time.txt](https://github.com/stats4sd/red-de-redes/files/9070008/01_incorrect_column_header_date_and_time.txt)

Generic error message and specific error message showed before processing file in queue.
As there are only Date and Time to be validated, it is not necessary to summarise the generic error message "There was an error on row 2." which showed twice. We may consider to do that when we have more validations added (um.... unlikely I think...)

image

image

**Comment by dan-tang-ssd** [comment]
[PASSED]

Testing performed for station 2 - 18, with same positive testing result as before.

I will perform testing for new met data files uploaded by UMSA in Apr and May 2022.

**Comment by dave-mills** [comment]
>Performed testing for station 1.
>Some records are already existed, click the "I confirm" checkbox, click "Confirm" button.
>Then error occured for duplicated record...

Ah, yes - I forgot that we need the "INSERT IGNORE" here, to ignore the duplicate submissions. Laravel query builder can only do IGNORE on individual inserts, not bulk inserts, (don't know why!), so I've swapped to using the DB::insert() facade in the FileController::storeFile.

**Review by dan-tang-ssd — APPROVED** [review]

**Pull request merged**
